{"name": "Valid Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"user-name\"]\"}\n  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000102ab44cc chromedriver + 4162764\n1   chromedriver                        0x0000000102aac654 chromedriver + 4130388\n2   chromedriver                        0x0000000102703bc0 chromedriver + 293824\n3   chromedriver                        0x000000010274a040 chromedriver + 581696\n4   chromedriver                        0x0000000102789ab0 chromedriver + 842416\n5   chromedriver                        0x000000010273d6bc chromedriver + 530108\n6   chromedriver                        0x000000010273e930 chromedriver + 534832\n7   chromedriver                        0x0000000102a79df8 chromedriver + 3923448\n8   chromedriver                        0x0000000102a7e3cc chromedriver + 3941324\n9   chromedriver                        0x0000000102a62028 chromedriver + 3825704\n10  chromedriver                        0x0000000102a7ef2c chromedriver + 3944236\n11  chromedriver                        0x0000000102a546e4 chromedriver + 3770084\n12  chromedriver                        0x0000000102a9b970 chromedriver + 4061552\n13  chromedriver                        0x0000000102a9bae8 chromedriver + 4061928\n14  chromedriver                        0x0000000102aac2d4 chromedriver + 4129492\n15  libsystem_pthread.dylib             0x000000019a2e026c _pthread_start + 148\n16  libsystem_pthread.dylib             0x000000019a2db08c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 11, in step_when_user_enters_valid_credentials\n    context.login_page.login(\"standard_user\", \"secret_sauce\")\n  File \"/Users/cintia/projects/AutoSauceWeb/pages/login_page.py\", line 14, in login\n    self.driver.find_element(*self.USERNAME_INPUT).send_keys(username)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user is on the login page", "status": "passed", "start": 1701910197186, "stop": 1701910197586}, {"name": "When the user enters valid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"user-name\"]\"}\n  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000102ab44cc chromedriver + 4162764\n1   chromedriver                        0x0000000102aac654 chromedriver + 4130388\n2   chromedriver                        0x0000000102703bc0 chromedriver + 293824\n3   chromedriver                        0x000000010274a040 chromedriver + 581696\n4   chromedriver                        0x0000000102789ab0 chromedriver + 842416\n5   chromedriver                        0x000000010273d6bc chromedriver + 530108\n6   chromedriver                        0x000000010273e930 chromedriver + 534832\n7   chromedriver                        0x0000000102a79df8 chromedriver + 3923448\n8   chromedriver                        0x0000000102a7e3cc chromedriver + 3941324\n9   chromedriver                        0x0000000102a62028 chromedriver + 3825704\n10  chromedriver                        0x0000000102a7ef2c chromedriver + 3944236\n11  chromedriver                        0x0000000102a546e4 chromedriver + 3770084\n12  chromedriver                        0x0000000102a9b970 chromedriver + 4061552\n13  chromedriver                        0x0000000102a9bae8 chromedriver + 4061928\n14  chromedriver                        0x0000000102aac2d4 chromedriver + 4129492\n15  libsystem_pthread.dylib             0x000000019a2e026c _pthread_start + 148\n16  libsystem_pthread.dylib             0x000000019a2db08c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 11, in step_when_user_enters_valid_credentials\n    context.login_page.login(\"standard_user\", \"secret_sauce\")\n  File \"/Users/cintia/projects/AutoSauceWeb/pages/login_page.py\", line 14, in login\n    self.driver.find_element(*self.USERNAME_INPUT).send_keys(username)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1701910197587, "stop": 1701910197597}, {"name": "And clicks the login button", "status": "skipped", "start": 1701910197598, "stop": 1701910197598}, {"name": "Then the user should be logged in successfully", "status": "skipped", "start": 1701910197598, "stop": 1701910197598}], "start": 1701910197186, "stop": 1701910197598, "uuid": "b5a9cda5-a0ac-45a5-afc2-eec4bd415f4a", "historyId": "3eb4405f3c1f9b79034cbd86eee86cd3", "fullName": "User Login: Valid Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}