{"name": "Invalid Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"user-name\"]\"}\n  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001032784cc chromedriver + 4162764\n1   chromedriver                        0x0000000103270654 chromedriver + 4130388\n2   chromedriver                        0x0000000102ec7bc0 chromedriver + 293824\n3   chromedriver                        0x0000000102f0e040 chromedriver + 581696\n4   chromedriver                        0x0000000102f4dab0 chromedriver + 842416\n5   chromedriver                        0x0000000102f016bc chromedriver + 530108\n6   chromedriver                        0x0000000102f02930 chromedriver + 534832\n7   chromedriver                        0x000000010323ddf8 chromedriver + 3923448\n8   chromedriver                        0x00000001032423cc chromedriver + 3941324\n9   chromedriver                        0x0000000103226028 chromedriver + 3825704\n10  chromedriver                        0x0000000103242f2c chromedriver + 3944236\n11  chromedriver                        0x00000001032186e4 chromedriver + 3770084\n12  chromedriver                        0x000000010325f970 chromedriver + 4061552\n13  chromedriver                        0x000000010325fae8 chromedriver + 4061928\n14  chromedriver                        0x00000001032702d4 chromedriver + 4129492\n15  libsystem_pthread.dylib             0x000000019a2e026c _pthread_start + 148\n16  libsystem_pthread.dylib             0x000000019a2db08c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 15, in step_when_user_enters_invalid_credentials\n    context.login_page.login(\"locked_out_user\", \"invalid_password\")\n  File \"/Users/cintia/projects/AutoSauceWeb/pages/login_page.py\", line 14, in login\n    self.driver.find_element(*self.USERNAME_INPUT).send_keys(username)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user is on the login page", "status": "passed", "start": 1701910622940, "stop": 1701910622998}, {"name": "When the user enters invalid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"user-name\"]\"}\n  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001032784cc chromedriver + 4162764\n1   chromedriver                        0x0000000103270654 chromedriver + 4130388\n2   chromedriver                        0x0000000102ec7bc0 chromedriver + 293824\n3   chromedriver                        0x0000000102f0e040 chromedriver + 581696\n4   chromedriver                        0x0000000102f4dab0 chromedriver + 842416\n5   chromedriver                        0x0000000102f016bc chromedriver + 530108\n6   chromedriver                        0x0000000102f02930 chromedriver + 534832\n7   chromedriver                        0x000000010323ddf8 chromedriver + 3923448\n8   chromedriver                        0x00000001032423cc chromedriver + 3941324\n9   chromedriver                        0x0000000103226028 chromedriver + 3825704\n10  chromedriver                        0x0000000103242f2c chromedriver + 3944236\n11  chromedriver                        0x00000001032186e4 chromedriver + 3770084\n12  chromedriver                        0x000000010325f970 chromedriver + 4061552\n13  chromedriver                        0x000000010325fae8 chromedriver + 4061928\n14  chromedriver                        0x00000001032702d4 chromedriver + 4129492\n15  libsystem_pthread.dylib             0x000000019a2e026c _pthread_start + 148\n16  libsystem_pthread.dylib             0x000000019a2db08c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 15, in step_when_user_enters_invalid_credentials\n    context.login_page.login(\"locked_out_user\", \"invalid_password\")\n  File \"/Users/cintia/projects/AutoSauceWeb/pages/login_page.py\", line 14, in login\n    self.driver.find_element(*self.USERNAME_INPUT).send_keys(username)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1701910622998, "stop": 1701910623002}, {"name": "And clicks the login button", "status": "skipped", "start": 1701910623002, "stop": 1701910623002}, {"name": "Then an error message should be displayed", "status": "skipped", "start": 1701910623002, "stop": 1701910623002}], "start": 1701910622940, "stop": 1701910623002, "uuid": "2adeeb44-567d-4036-9661-2a24eb043dc0", "historyId": "afd74eba4c55c0465f70568d7d0d15b9", "fullName": "User Login: Invalid Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}